### ISSUE TITLE
Conflicting licenses

### ISSUE THREAD

**Issue by sandra-thieme** [railnova/osrm-train-profile#2]
Hi,

it is stated in [README.md](https://github.com/C4ptainCrunch/osrm-train-profile#license) and [LICENSE.md](https://github.com/C4ptainCrunch/osrm-train-profile/blob/master/LICENSE.md) that this project is licensed under the 2-clause BSD license. But the lua files have an AGPL header:
```
-- This code was written by Nikita Marchant <nikita.marchant@gmail.com>
-- Code under the AGPL license https://www.gnu.org/licenses/agpl-3.0.html
```

Can you please clarify?

**Comment by C4ptainCrunch** [comment]
Hi, 

Everything is now under the 2-Clause BSD licence. Is it good for you ? :)
